### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by ashleyconnor** [tinygrasshopper/one_offs#3]
Rails 4 has moved away from white-listing parameters in the model to using `strong parameters` in controllers.

Your gem still works with Rails 4 but requires the following to your `Gemfile`

`gem 'protected_attributes'`

I can create a pull request to add Rails 4 support without using this gem if you'd like?

**Comment by tinygrasshopper** [comment]
Yes please.

I can merge it and create a major version for rails 4.

**Comment by ashleyconnor** [comment]
https://github.com/akshaymankar has already done this.

I'll create a pull-request shortly, but all credit goes to him.

**Comment by tinygrasshopper** [comment]
Resolved by #4
